-- MySQL Script generated by MySQL Workbench
-- Thu Dec 14 22:35:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema csc667Unodb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `csc667Unodb` ;

-- -----------------------------------------------------
-- Schema csc667Unodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csc667Unodb` DEFAULT CHARACTER SET utf8 ;
USE `csc667Unodb` ;

-- -----------------------------------------------------
-- Table `csc667Unodb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `csc667Unodb`.`users` ;

CREATE TABLE IF NOT EXISTS `csc667Unodb`.`users` (
  `id` INT GENERATED ALWAYS AS () VIRTUAL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc667Unodb`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `csc667Unodb`.`game` ;

CREATE TABLE IF NOT EXISTS `csc667Unodb`.`game` (
  `gid` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NOT NULL,
  `created` TIMESTAMP NOT NULL,
  `game_title` VARCHAR(255) NOT NULL,
  `player_id` INT NOT NULL,
  `player_un` VARCHAR(255) NOT NULL,
  `player_count` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`gid`),
  UNIQUE INDEX `gid_UNIQUE` (`gid` ASC) VISIBLE,
  INDEX `id_idx` (`owner_id` ASC) VISIBLE,
  INDEX `id_idx1` (`player_id` ASC) VISIBLE,
  INDEX `username_idx` (`player_un` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`owner_id`)
    REFERENCES `csc667Unodb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`player_id`)
    REFERENCES `csc667Unodb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `username`
    FOREIGN KEY (`player_un`)
    REFERENCES `csc667Unodb`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc667Unodb`.`card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `csc667Unodb`.`card` ;

CREATE TABLE IF NOT EXISTS `csc667Unodb`.`card` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NOT NULL,
  `played` VARCHAR(255) NOT NULL,
  `card_type` INT NOT NULL,
  `card_action` VARCHAR(255) NULL,
  `card_back` BLOB NULL,
  `card_front` BLOB NULL,
  PRIMARY KEY (`cid`),
  UNIQUE INDEX `cid_UNIQUE` (`cid` ASC) VISIBLE,
  INDEX `id_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`owner_id`)
    REFERENCES `csc667Unodb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc667Unodb`.`deck`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `csc667Unodb`.`deck` ;

CREATE TABLE IF NOT EXISTS `csc667Unodb`.`deck` (
  `did` INT NOT NULL AUTO_INCREMENT,
  `game_id` INT NOT NULL,
  `cards` INT NOT NULL,
  PRIMARY KEY (`did`),
  UNIQUE INDEX `did_UNIQUE` (`did` ASC) VISIBLE,
  INDEX `gid_idx` (`game_id` ASC) VISIBLE,
  INDEX `cid_idx` (`cards` ASC) VISIBLE,
  CONSTRAINT `gid`
    FOREIGN KEY (`game_id`)
    REFERENCES `csc667Unodb`.`game` (`gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cid`
    FOREIGN KEY (`cards`)
    REFERENCES `csc667Unodb`.`card` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc667Unodb`.`discard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `csc667Unodb`.`discard` ;

CREATE TABLE IF NOT EXISTS `csc667Unodb`.`discard` (
  `discard_id` INT NOT NULL AUTO_INCREMENT,
  `game_id` INT NOT NULL,
  `cards` INT NOT NULL,
  PRIMARY KEY (`discard_id`),
  INDEX `cid_idx` (`cards` ASC) VISIBLE,
  INDEX `gid_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `cid`
    FOREIGN KEY (`cards`)
    REFERENCES `csc667Unodb`.`card` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gid`
    FOREIGN KEY (`game_id`)
    REFERENCES `csc667Unodb`.`game` (`gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc667Unodb`.`hand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `csc667Unodb`.`hand` ;

CREATE TABLE IF NOT EXISTS `csc667Unodb`.`hand` (
  `hid` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NOT NULL,
  `card_id` INT NOT NULL,
  PRIMARY KEY (`hid`),
  INDEX `id_idx` (`owner_id` ASC) VISIBLE,
  INDEX `cid_idx` (`card_id` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`owner_id`)
    REFERENCES `csc667Unodb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cid`
    FOREIGN KEY (`card_id`)
    REFERENCES `csc667Unodb`.`card` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;